version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - setup_remote_docker

      - run:
          shell: /bin/bash
          command: |
            if [ "$CIRCLE_BRANCH" == 'master' ]; then
              mvn -Dpapertrail.packagecloud.url="$env.PACKAGECLOUD_URL" \
                  -Dpapertrail.packagecloud.snapshots.url="$env.PACKAGECLOUD_SNAPSHOT_URL" \
                  -s .circleci/m2/settings.xml \
                  -DskipTests \
                  deploy
            fi

workflows:
  version: 2
  build_test_release:
    jobs:
      - build
      - integration-test:
          requires:
            - build
      - unit-test:
          requires:
            - build
      - release:
          requires:
            - integration-test
            - unit-test
